### ISSUE TITLE
Works with 2.9 version

### ISSUE THREAD

**Issue by leoborlot** [thirdset/ThirdSetMauticResetBundle#2]
Hello. 

This will work to the 2.9.* versions?

**Comment by collinkrawll** [comment]
Sorry, I'm not sure. We haven't tried it.

If you are able to, please try it (on a test database) and report back.

**Comment by leoborlot** [comment]
yes, I will try it and callback here.

**Comment by mjlogan** [comment]
Running on 2.9.2 with no problems.

**Comment by collinkrawll** [comment]
I added a Compatibility section to the README.md file and it now indicates that the plugin works with up to v2.9.2 of Mautic.
