### ISSUE TITLE
Reset emails sent

### ISSUE THREAD

**Issue by Belgor** [thirdset/ThirdSetMauticResetBundle#4]
Hello,
the plugin is fine, but I have a problem to repeatedly send emails from the Campaign that has been reset.

It seems like Mautic do not send email to the same contact twice if it has already record in DataBase Table "###_email_stats"
Connection to that Campaign is "source = campaign.event" "source_id = campaign_event_id"

**Comment by collinkrawll** [comment]
Hi, @Belgor, I just fully tested the plugin with the latest version of Mautic (v2.11.0) and everything worked for me.

I thought of what might be causing your issue though. In your Send Email Campaign action, what Email Type do you have selected? You'll want to use the "Transactional" Email Type as "Marketing" won't work. This is as designed - see the tooltip help next to the Email Type field for more info about how these two Email Types work and when they should be used.
