### ISSUE TITLE
Tags are removed after processing

### ISSUE THREAD

**Issue by Fade59** [thirdset/ThirdSetMauticResetBundle#5]
of course the tags get removed after the processing but as soon as all contacts are processed the tag is completely removed from mautic and can not be added again in a Campaign until I manually create the tag. Is there a Workaround for this?

**Comment by Fade59** [comment]
As a workaround i used the Method in this Thread to protect the tags from deletion:

https://stackoverflow.com/questions/8684979/protect-row-from-deletion-in-mysql

**Comment by collinkrawll** [comment]
Can you explain this a bit more? The plugin is constantly removing all tags and then adding them again and it seems to work fine. What happens for you (before your workaround)?

**Comment by collinkrawll** [comment]
Closing this issue. Please open a new one if you think there is still an issue (please see my questions above too). Thanks!

**Comment by collinkrawll** [comment]
This is now fixed. Please upgrade to v1.1.2.
