### ISSUE TITLE
The "rest_[campaignID" is also being deleted from thee campaign itself

### ISSUE THREAD

**Issue by raymondkent** [thirdset/ThirdSetMauticResetBundle#6]
Hi there,

Thanks so much for this plugin.

I have set it up and managed to get it to run using cron job.

I had a modify tag the second last step in the campaign, where I added in the Modify tag  ADD TAG and created the tag "reset_[campaignID]" to tag the contact. This same action also removes the !NewVIP tag and adds on !VIP tag.

So this ONE action should adds two new tags   !VIP   and    reset_[id]  and remove the !NewVIP tag.

I also had a remove contact from this campaign action just after the modify tag above.

The cron job executes and the process runs, BUT when I go back and look at the Campaign the tag that is supposed to be added "reset_campaingID" has also been removed from the campaign.

In fact it seems that the reset tag is also getting deleted from the list of all available tags -I think this could be the main issue?

I am on Mautic 2.12.1.

USE CASE:
The campaign is driven by a VIP Campaign signup form from my wordpress ecom store.

I tag them with  !NewVIP  whenever the form is submitted.

Step 1 is that the campaign tests to see if they are already a  !VIP  if so the !NewVIP tag is deleted and they go down a specific path letting them know they are already a VIP.

If they aren't already tagged as a !VIP THEN  then they get sent an indoctrination sequence of emails. 

When this indoctrination sequence completes, they are then tagged as a !VIP and the original !NewVIP tag is removed.

I also remove them from the campaign.

BUT - It is possible they might try and sign up again from the page at another date time. This is why I want to be able to let them back in to the campaign because IF they do resubmit, then the test at the start will see they are already flagged as a !VIP and send them a different email.

Anyway. 

The issue is the "reset_" tag that I add in the campaign builder is being deleted from the campaign itself and also from the list of available tags once the cron job runs.

I hope this makes sense.

**Comment by collinkrawll** [comment]
This seems to be the same as Issue #5.

It seems to be an issues with Mautic itself as this plugin is simply removing the tag from the lead and then saving the lead:

https://github.com/thirdset/ThirdSetMauticResetBundle/blob/817949f09b59e428cfa129c4286e3b79d26cd571/Command/ProcessResetsCommand.php#L144
https://github.com/thirdset/ThirdSetMauticResetBundle/blob/817949f09b59e428cfa129c4286e3b79d26cd571/Command/ProcessResetsCommand.php#L145

 Apparently when you untag the last lead with a given tag, Mautic (or Doctrine) decides that the tag is orphaned and deletes it. 

We'll work on a fix. In the meantime, please try the workaround suggested in Issue #5.

**Comment by raymondkent** [comment]
Hi Colin,

Thanks for the heads up but to be honest it's above my capability to actually implement the suggestions.

I am not a programmer.

I have no idea where to 'create' the commands or how to make it work.

**Comment by collinkrawll** [comment]
This is now fixed. Please upgrade to v1.1.2.
