### ISSUE TITLE
Not working on Mautic v2.12.1

### ISSUE THREAD

**Issue by xtjoeywx** [thirdset/ThirdSetMauticResetBundle#7]
Thank you for making this great plugin. I want you to know that saw that the current compatibility for this is on Mautic v2.11.0, but I really wanted this to work with my current version of 2.12.1 so I thought I'd give it a try. I could really use this, but unfortunately no luck. The contacts show back up in the campaign, but nothing happens after that.

This is how I tested it: I used a tag called "test tag" to filter three contacts into the "Test segment" which also automatically added them to the "Test campaign". The campaign completed and I manually removed the three contacts from the Test segment and the Test campaign. Then I added a tag called "reset_3" (3 is the Test campaign's ID number) to each of the three contacts. I also re-used the "test tag" to put the three contacts back into the Test Segment and they automatically showed back up in the Test Campaign. It looked good until nothing happened. It was supposed to send the same email after two minutes, but it didn't. 

So, either I did something wrong or it simply isn't compatible with my version of Mautic. Am I supposed to create a new segment that filters "reset_3" instead of "test tag"?

Update (Edit): I tried it with the "reset_3" tag only on each contact. Then I created a new segment that filtered that tag to the original campaign and it still didn't work. Also, I noticed something strange in the history of each contact. Each time I tried sending it back through the campaign it looks as if my last event (contact history) repeated itself. In other words, my last event was me changing the contact to a stage to "New". It shows "New" four times in the history. I know it's related because the timestamp is at the same times I tried to send the campaign. My first action inside my campaign builder is to change the stage from "New" to "Contacted".

**Comment by collinkrawll** [comment]
Did you ever [run the process-resets command](https://github.com/thirdset/ThirdSetMauticResetBundle#run-the-process_resets-command)?

The process-resets command is where the magic happens. It finds all contacts tagged with reset_3 and deletes their history for campaign 3. This allows them to be processed through the campaign again.

Also, I just tested the plugin with Mautic 2.12.0 and it works fine, so it's likely that you just need to run the process-resets command.

**Comment by xtjoeywx** [comment]
I must have missed that part of the instructions. Thank you. Do I need to run this command before each time? If so, could you please give an example of what a cron job would look like that runs the process resets command?

**Comment by collinkrawll** [comment]
No problem. Yes, the command is what resets the contact's history for the campaign. You tag the contacts that you want to reset and then run the command. When the command is run, it finds all contacts with the tag and clears their history for the campaign (so that they can go through it again).

Here's an example cron job that runs the command daily at 1 AM:

```
0 1 * * * php /path/to/mautic/app/console mautic:campaigns:process_resets
```

Here's more info about Mautic cron jobs: https://mautic.org/docs/en/setup/cron_jobs.html
