### ISSUE TITLE
Setting up a daily newsletter campaign

### ISSUE THREAD

**Issue by ghost** [thirdset/ThirdSetMauticResetBundle#8]
Hello there,

This is actually not an 'issue' but I'm just trying to get my head around how to use your plugin. I want to set up a newsletter to go out say 10 am every morning. I have my newsletter email set up as a campaign email, tags are properly attached to contacts in the contact segment. Now my issue is how to set up the campaign to send emails out at a given time. Yes I've marked the emails as transactional emails too. Do I set up those emails to go out immediately, at a relative time period or at a specific date/time? If it's either one or two (even 3) how can I make sure they go at 10am? Any help in this regards is highly appreciated.

Thanks

**Comment by collinkrawll** [comment]
Hi, for a newsletter, you actually don't want to use Campaigns. Instead, make a Segment for newsletter subscribers. Then create Segment Emails to go to the newsletter subscriber Segment. When you create the Segment Email you can pick the start date and time (such as 10 am).

To create a Segment Email:

1.  Go to Channels and then Emails
2.  Click the "New" button.
3.  Choose "New Segment Email"

There is more information on Segment Emails on the Mautic website [here](https://mautic.com/help/create-segment-email/).

**Comment by ghost** [comment]
Hello Collin,

On my Mautic instance I don't have the Schedule option for Segment Mails.
It's a hosted instance running version 2.13.2. That's why I thought I may
have to use the campaign option. Or am I missing something in here?
--
Most of the important things in the world have been accomplished by people
who have kept on trying when there seemed to be no hope at all - Dale
Carnegie

**Comment by collinkrawll** [comment]
It should just be a "Publish At" field. Set that to the date/time when you want the email to go out.  This is the post that I used when I first got into Segment Emails: 

https://innotiom.com/sending-newsletters-with-mautic/

If you don't have those functions/controls, I would talk to Mautic directly (or whomever you get your hosted instance from).

**Comment by ghost** [comment]
Thanks again for the reply and the link to a great article. I think I didn't describe it properly in my very first message. What I'm trying to do is to set this email newsletter to go out EVERYDAY at let's say 10 am. If I set up a segment email to go out tomorrow morning at 10 am, it will send out, but how can I automate the rest of the delivery (everyday) using your plugin? That's what I'm struggling to understand as on the Usage section it says something about using Campaigns.

**Comment by collinkrawll** [comment]
I guess I don't understand, are you intending to send the same newsletter (with the same content, subject, etc) every day?

**Comment by ghost** [comment]
Technically yes. It's a newsletter based on a RSS feed so the content get
dynamically changed without having for us to do anything manually. I was
given the info of your plugin by the RSS feed plugin developer. Hope this
makes sense now.
--
Most of the important things in the world have been accomplished by people
who have kept on trying when there seemed to be no hope at all - Dale
Carnegie

**Comment by collinkrawll** [comment]
Oh, okay, I'm not familiar with that plugin and haven't tried using Mautic for something like what you are describing, but we have another plugin that might help. 

Check out the [ThirdSetMauticTimingBundle](https://github.com/thirdset/ThirdSetMauticTimingBundle) plugin. It allows you to set a time on your Campaign Events. That aught to handle the 10 AM part. 

This plugin (ThirdSetMauticResetBundle) could probably get your contacts to go through the campaign multiple times. 

And you could probably then use the third plugin to generate the emails from RSS.
